### ISSUE TITLE
Method net.andreinc.neatchess.client.processor.BestMoveProcessor#process throws UCIRuntimeException when no ponder is returned

### ISSUE THREAD

**Issue by Michal299** [nomemory/neat-chess#2]
# Description
Method `net.andreinc.neatchess.client.processor.BestMoveProcessor#process` throws 
```
net.andreinc.neatchess.client.exception.UCIRuntimeException: Cannot find best movement in engine output!
```
exception when stockfish return no ponder.

# Steps to reproduce
```
var uci = new UCI();
uci.startStockfish();
uci.uciNewGame();
uci.positionFen("Q1b3kr/p1p1P1p1/3p2Bp/8/P4N2/8/1PP2PPP/R1B1R1K1 w - - 3 25");
System.out.println(uci.bestMove(18).getResultOrThrow());
```
# Actual result
```
Exception in thread "main" net.andreinc.neatchess.client.exception.UCIRuntimeException: net.andreinc.neatchess.client.exception.UCIRuntimeException: Cannot find best movement in engine output!

	at net.andreinc.neatchess.client.UCI.lambda$command$1(UCI.java:127)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: net.andreinc.neatchess.client.exception.UCIRuntimeException: Cannot find best movement in engine output!

	at net.andreinc.neatchess.client.processor.BestMoveProcessor.lambda$process$0(BestMoveProcessor.java:19)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.andreinc.neatchess.client.processor.BestMoveProcessor.process(BestMoveProcessor.java:19)
	at net.andreinc.neatchess.client.UCI.lambda$command$1(UCI.java:124)
	... 10 more
```

# Expected result
Valid move should be returned, for example `a8c8`, which is mate.

# Returned value from stockfish
```
go bestmove depth 18
info string NNUE evaluation using nn-6877cd24400e.nnue enabled
info depth 1 seldepth 1 multipv 1 score mate 1 nodes 196 nps 196000 tbhits 0 time 1 pv a8c8
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 390 nps 390000 tbhits 0 time 1 pv a8c8
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 582 nps 582000 tbhits 0 time 1 pv a8c8
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 774 nps 774000 tbhits 0 time 1 pv a8c8
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 966 nps 483000 tbhits 0 time 2 pv a8c8
info depth 6 seldepth 2 multipv 1 score mate 1 nodes 1158 nps 579000 tbhits 0 time 2 pv a8c8
info depth 7 seldepth 2 multipv 1 score mate 1 nodes 1350 nps 675000 tbhits 0 time 2 pv a8c8
info depth 8 seldepth 2 multipv 1 score mate 1 nodes 1542 nps 771000 tbhits 0 time 2 pv a8c8
info depth 9 seldepth 2 multipv 1 score mate 1 nodes 1734 nps 867000 tbhits 0 time 2 pv a8c8
info depth 10 seldepth 2 multipv 1 score mate 1 nodes 1926 nps 963000 tbhits 0 time 2 pv a8c8
info depth 11 seldepth 2 multipv 1 score mate 1 nodes 2118 nps 1059000 tbhits 0 time 2 pv a8c8
info depth 12 seldepth 2 multipv 1 score mate 1 nodes 2310 nps 1155000 tbhits 0 time 2 pv a8c8
info depth 13 seldepth 2 multipv 1 score mate 1 nodes 2502 nps 834000 tbhits 0 time 3 pv a8c8
info depth 14 seldepth 2 multipv 1 score mate 1 nodes 2694 nps 898000 tbhits 0 time 3 pv a8c8
info depth 15 seldepth 2 multipv 1 score mate 1 nodes 2886 nps 962000 tbhits 0 time 3 pv a8c8
info depth 16 seldepth 2 multipv 1 score mate 1 nodes 3078 nps 1026000 tbhits 0 time 3 pv a8c8
info depth 17 seldepth 2 multipv 1 score mate 1 nodes 3270 nps 1090000 tbhits 0 time 3 pv a8c8
info depth 18 seldepth 2 multipv 1 score mate 1 nodes 3464 nps 1154666 tbhits 0 time 3 pv a8c8
bestmove a8c8
```

**Comment by Michal299** [comment]
After quick investigation I found that the reason is in `net.andreinc.neatchess.client.parser.BestMoveParser#BEST_MOVE_REGEX` which assumes that there is always a ponder returned with `bestmove`.

![image](https://user-images.githubusercontent.com/60276981/186502917-4c9b5e81-e58e-4c87-b3b7-38649cc7bc0c.png)
After filtering lines in `net.andreinc.neatchess.client.processor.BestMoveProcessor#process` we get empty `Optional` object, which cause that exception is thrown.

**Comment by Michal299** [comment]
Fix example: https://github.com/Michal299/slick-chess/commit/9ee2cb193d3eb3e302ce1e6865d843d97fec6b75#diff-766d9c46073e300806f2d430b5735f70e7496ee5571023f8bf82b22262bca9e8
