### ISSUE TITLE
UCIRuntimeException (Cannot find best move)

### ISSUE THREAD

**Issue by jaylawl** [nomemory/neat-chess#8]
Using Stockfish 15, I am getting this exception:

```java
Exception in thread "AWT-EventQueue-0" net.andreinc.neatchess.client.exception.UCIRuntimeException: net.andreinc.neatchess.client.exception.UCIRuntimeException: Cannot find best movement in engine output!

	at net.andreinc.neatchess.client.UCI.lambda$command$1(UCI.java:127)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: net.andreinc.neatchess.client.exception.UCIRuntimeException: Cannot find best movement in engine output!

	at net.andreinc.neatchess.client.processor.BestMoveProcessor.lambda$process$0(BestMoveProcessor.java:19)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.andreinc.neatchess.client.processor.BestMoveProcessor.process(BestMoveProcessor.java:19)
	at net.andreinc.neatchess.client.UCI.lambda$command$1(UCI.java:124)
	... 10 more
Caused by: net.andreinc.neatchess.client.exception.UCIRuntimeException: Cannot find best movement in engine output!
```

This is happening here in my code: 
```java
    private void autoPlayEngine() {

        this.uci.uciNewGame();

        final String stringedFen = Fen.fromBoard(this.board).toString();
        System.out.println("Sending FEN to engine: " + stringedFen);
        this.uci.positionFen(stringedFen);

        // Exception thrown on either of these lines (i can't tell):
        final UCIResponse<BestMove> uciResponse = this.uci.bestMove(10, 3000);
        System.out.println("Best move: " + uciResponse.getResultOrThrow()); 
        
        // rest of my method
    }
```

I have ensured that the FEN i'm sending is correct.

This issue happens often in the late-endgame for whatever reason.
And it always happens if stockfish has mate-in-one with either pieces. It appears to be unable to deliver the mate.

//

[Example position with thrown exception](https://i.gyazo.com/72a20861487b5d4b764a84f10c2c0356.png)
I was letting stockfish play a game against itself automatically. Auto play was enabled, which for my application means that there is a clock thread which prompts the configured chess engine to make a move every second. But on this final move, stockfish timed out. Thus, i disabled auto play and send the command to make a move manually (which runs the same code, just not on a clock) - and the exception is thrown.

//update 1:
I was able to determine that the exception is thrown by trying to get the best move without checking `UCIResponse#success()`.
However, no matter how many times tried, it is still incapable of performing mate-in-one.

//update 2:
I think this happens because of pondering.
Did the following:
- Started a stockfish instance in windows CMD
- input the FEN
- input "go ponder"
- input "go bestmove"
- >>> no response!

However, if i leave out "go ponder", it will return a move properly.
This is confusing, because i did not set stockfish to ponder. And when launching stockfish via...
```java
this.uci = new UCI();
this.uci.start("C:\\Users\\Admin\\Desktop\\stockfish_15.1_win_x64_popcnt\\stockfish.exe");
```
... it prints that pondering is turned off:
`Ponder: CheckEngineOption{name='Ponder', defaultValue=false}`

**Comment by jaylawl** [comment]
I have now funked up my own (simple) chess engine / uci interface and i am not experiencing the same issue. I am certain it must be a problem with this code base.

**Comment by Modris** [comment]
I had the same problem. Could not get it to work with the bestmove for 1 move mates at all.  You can "solve" this by using Analysis mode instead and then getting the bestmove from there.

Maybe the issue is that the Stockfish.exe engine bestmove search ("go movetime...") will usually return an output like "bestmove h5f6 ponder d8f6". But 1 move mate returns "bestmove c7d8" without the ponder part. But i'm no expert to go search the code to pinpoint where the exact problem is. 

I also ended up writing my own UCI engine parsing.
